### PR TITLE
Implemented spotify webapi for search page functionality

### PR DESCRIPTION
**Pull request by JZ0ro**

### CODE REVIEW

**Review by k3liang — CHANGES_REQUESTED** [review]
should not be storing client id and client secret
is start dependency needed?

**Comment by JZ0ro** [comment]
Would replacing the client ID and client secret in the .env with MY client ID and secret be sufficient to solve the issue of my client ID and secret being visible?

**Comment by k3liang** [comment]
my client id and secret in the .env file should be good. Just remove anything like from the actual source code and then get my client id and secret with process.env.CLIENT_ID and process.env.CLIENT_SECRET
also remove the axios dependency because I don't think you are using it either.

**Comment by k3liang** [comment]
additionally, you can look at my code, and you'll see that I have an easy way of calling the spotify endpoints, so you don't have to repeat code like for getting the albums:
just `await fetch(/userinfo?url=[Spotify API endpoint url])`

**Comment by JZ0ro** [comment]
so update,

when I use your client id and secret, I get this following error:
image

But this error disappears when I use my client id and secret.  As a work around I was thinking of creating a separate client id variable and client secret var in the .env file and calling it from my file that uses the search engine. Any thoughts on this approach?

**Comment by k3liang** [comment]
can u please commit and push the buggy code? As well as tell me how to reproduce the bug.

**Review by k3liang — APPROVED** [review]
LGTM, i'll make some adjustments to backend endpoints, so you can call those endpoints instead of having repetitive code in the front end

**Pull request merged**
