### PR TITLE
Updated spotify utils

### PR DESCRIPTION
**Pull request by JZ0ro**
Updated spotify utils to allow the refresh of spotify token

### CODE REVIEW

**Comment by k3liang** [comment]
Correction: 
`spotify-utils.ts` already allows the refresh of a spotify token, your update should be an update to the scope of what our web app can access

**Review by k3liang — CHANGES_REQUESTED** [review]
it appears that the code wasn't actually changed

update the scope to handle "streaming"

**Comment by JZ0ro** [comment]
updated the scope variable to handle streaming

please let me know if this was the correct way to go about doing that

**Comment by k3liang** [comment]
redundant, already changed in another branch

**Pull request closed without merging**
